version: '3'
services:
  omnia:
    image: ghcr.io/chronicleprotocol/omnia_relay:latest
    volumes:
      - "~/.ethereum:/home/omnia/.ethereum"
      - "~/omnia-config/omnia.json:/home/omnia/omnia.json"

      - "~/ssb-config/config:/home/omnia/.ssb/config"
      - "~/ssb-config/secret:/home/omnia/.ssb/secret"

    environment:
      SSB_KEYS: "/home/omnia/.ssb/secret"
      SSB_CONF: "/home/omnia/.ssb/config"
      SSB_HOST: "ssb-server.local"
      SSB_PORT: "8007"
      OMNIA_VERBOSE: "true"
      OMNIA_MODE: "RELAY"
